- name: "Extra Components used by Applications"
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: "Download Sonatype nexus manifest"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/redhat-scholars/tekton-tutorial/master/install/utils/nexus.yaml"
        dest: "{{ work_dir }}/nexus.yaml"
    
    - name: "Deploy Nexus"
      kubernetes.core.k8s:
        state: present
        src: "{{ work_dir }}/nexus.yaml"
        namespace: default
        wait: yes
        wait_timeout: 600
        context: "{{ item.value.k8s_context }}"
      loop: "{{ gloo_clusters | dict2items}}"
      loop_control:
        label: "{{ item.key }}"
      when: item.key != 'mgmt'

    - name: "Add a bitnami repository"
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
    
    - name: "Deploy Postgresql (fruits-api)"
      kubernetes.core.helm:
        release_name: postgresql
        chart_ref: bitnami/postgresql
        release_namespace: default
        create_namespace: yes
        values:
          global:
            postgresql: 
              postgresqlDatabase: fruitsdb
              postgresqlUsername: postgres
              postgresqlPassword: password
              servicePort: 5432
            initdbScriptsConfigMap: postgres-schema
        update_repo_cache: yes
        context: "{{ item.value.k8s_context }}"
        wait: yes
      loop: "{{ gloo_clusters | dict2items}}"
      loop_control:
        label: "{{ item.key }}"
      when: item.key != 'mgmt'
   
    - name: "Deploy db adminer"
      kubernetes.core.k8s:
        definition: "{{ lookup('kubernetes.core.kustomize', dir= playbook_dir + 'extras/dbadminer' ) }}"

        