---
roles:
  - name: kameshsampath.minikube
collections:
  - name: kameshsampath.gloo
  - name: community.crypto
  - name: ansible.posix 
    version: '>=1.2.0'
  - name: community.general
    version: '>=1.2.0'
  - name: kubernetes.core
    version: '>=2.2.0'
