---
roles:
  - name: kameshsampath.minikube
    src: https://github.com/kameshsampath/ansible-role-minikube
    revision: main
collections:
  - name: kameshsampath.gloo
    src: https://github.com/kameshsampath/kameshsampath.gloo
    revision: main
  - name: community.crypto
  - name: ansible.posix 
    version: '>=1.2.0'
  - name: community.general
    version: '>=1.2.0'
  - name: kubernetes.core
    version: '>=2.2.0'
